"""alter orders total_price type

Revision ID: d858ed41effd
Revises: da89c4998b90
Create Date: 2026-02-11 17:20:32.032756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd858ed41effd'
down_revision: Union[str, Sequence[str], None] = 'da89c4998b90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'total_price',
               existing_type=sa.NUMERIC(precision=15, scale=5),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'total_price',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=15, scale=5),
               existing_nullable=False)
    # ### end Alembic commands ###
