"""add orders

Revision ID: 90f5d5c55138
Revises: b2d218114e2b
Create Date: 2026-02-11 12:31:46.557651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90f5d5c55138'
down_revision: Union[str, Sequence[str], None] = 'b2d218114e2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=15, scale=5), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'SHIPPED', 'CANCELED', name='orderstatus'), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_items_product_id_gin', 'orders', [sa.literal_column("(items['products'])")], unique=False, postgresql_using='gin', postgresql_ops={'products': 'jsonb_ops'})
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index('idx_items_product_id_gin', table_name='orders', postgresql_using='gin', postgresql_ops={'products': 'jsonb_ops'})
    op.drop_table('orders')
    # ### end Alembic commands ###
